spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/giftlist
    username: postgres
    password: parola1d2t3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true



server.port: 5000

  # security config
security:
  jwt:
     issuer : Nurgazy
     secret-word: veryveryveryveryverysecretword
     expires-at: 30

springdoc:
  swagger-ui:
    path: /swagger